#!/bin/sh
#

# This hook Modifies Build Number for the main branch after a merge
# The branch name should start with the prefix main
# Additional commit is added to the main branch to increment the build number
# Build Number is patched over higher numbers 
# For Ex: 7.0.2051.000 -> 7.0.2052.000

currentBranch=$(git rev-parse --abbrev-ref HEAD)

if [[ $currentBranch == main* ]]; then
    
    buildNumberFile="buildNumber.txt"

	# check if file exists
	if [ -f "$buildNumberFile" ]; then
		echo "Current build number: $buildNumber"

		# Split the build number into a,b,c,d
		IFS='.' read -r a b c d <<< "$buildNumber"

		# Increment the lower number (d)
		c=$((c+1))
		newBuildNumber="$a.$b.$c.$d"
		echo "New build number: $newBuildNumber"

		# Save the new build number back to the file
		echo "$newBuildNumber" > "$buildNumberFile"

		# Stage the build number file
		git add "$buildNumberFile"

        git commit -m "Updated Build Number"
		exit 0
	else
		echo "Build number file ($builNumberFile) not found!"
		exit 1
	fi
fi