#!/bin/sh
#

# This hook Modifies Build Number for release branches before a commit
# The branch name should start with the prefix release
# Build Number is patched over lower numbers 
# For Ex: 7.0.2051.000 -> 7.0.2051.001

currentBranch=$(git rev-parse --abbrev-ref HEAD)

if [[ $currentBranch == release* ]]; then
	buildNumberFile="buildNumber.txt"

	# check if file exists
	if [ -f "$buildNumberFile" ]; then
		echo "Current build number: $buildNumber"

		# Split the build number into a,b,c,d
		IFS='.' read -r a b c d <<< "$buildNumber"

		# Increment the lower number (d)
		d=$((d+1))
		newBuildNumber="$a.$b.$c.$d"
		echo "New build number: $newBuildNumber"

		# Save the new build number back to the file
		echo "$newBuildNumber" > "$buildNumberFile"

		# Stage the build number file
		git add "$buildNumberFile"

		exit 0
	else
		echo "Build number file ($builNumberFile) not found!"
		exit 1
	fi
fi
